trigger:
- master

stages:
- stage: Build
  jobs:
  - job: 'Build'
    displayName: 'Build the product'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
    steps:
        - task: UseDotNet@2
          displayName: 'Use .Net Core'
          inputs:
            version: '3.1.x'
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'dotnet publish'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            zipAfterPublish: True

- stage: PrepareArtifact
  jobs:
  - job: 'PreparaArtifact'
    displayName: 'Prepare artifact'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
    steps:
        - task: CopyFiles@2
          displayName: 'Copy files'
          inputs:
            SourceFolder: 'Infrastructure'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)/Infrastructure'
            CleanTargetFolder: true
            OverWrite: true
        - task: PublishBuildArtifacts@1
          displayName: 'Publish artifact'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'